export const photos = {
  og: "/marketing/01.png",
  heroDesktop: "/marketing/02.png",
  heroMobile: "/marketing/03.png",
  randomPeer: "/marketing/04.png",
  randomSelf: "/marketing/05.png",
  liveHost: "/marketing/06.png",
  live1: "/marketing/07.png",
  live2: "/marketing/08.png",
  live3: "/marketing/09.png",
  live4: "/marketing/10.png",
  dating: "/marketing/11.png",
  chat: "/marketing/12.png",
  auth: "/marketing/13.png",
  about: "/marketing/14.png",
  safety: "/marketing/15.png",
  help: "/marketing/16.png",
  pricing: "/marketing/17.png",
  extra: "/marketing/18.png",
} as const;
